"""Custom exception hierarchy for HARA."""

from __future__ import annotations


class HARAError(Exception):
    """Base class for all HARA-raised exceptions."""


class ConfigError(HARAError):
    """Configuration is invalid or incomplete."""


class ConnectorError(HARAError):
    """Connector failed to initialize or operate."""


class ProviderError(HARAError):
    """Provider failed to initialize or call."""


class SQLValidationError(HARAError):
    """SQL generated by LLM failed safety validation (sqlglot AST)."""


class IngestError(HARAError):
    """Raised by the ingest pipeline when input cannot be processed."""


class SemanticMapError(HARAError):
    """Raised by the semantic map service (missing data, invalid YAML, etc.)."""
